name: Hello World

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say Hello
        run: echo "Hello form git actions"
