name: Hello World

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello form Github Actions"


      - name: list files
        run: ls -la


